### ISSUE TITLE
Where will the video be saved?

### ISSUE THREAD

**Issue by AvanishCodes** [infinitecoder1729/screen-recorder-python#2]
https://github.com/infinitecoder1729/screen-recorder-python/blob/bd4360faedf5a87ee3358db8654948421804e99a/screen%20recorder.py#L22

**Comment by infinitecoder1729** [comment]
The file gets saved in the same folder where your python script is saved.
However you can specify your own path using :
video = cv.VideoWriter(" **path\Screen Recording {} .avi** ".format(dtstamp),cv.VideoWriter_fourcc(*'MJPG'),20, size) in line 8 of the code.

**Comment by AvanishCodes** [comment]
It is not working on a WSL system, operated from Windows Side.

**Comment by infinitecoder1729** [comment]
Possible Issues and Solutions :
1. File name can be an issue :
> Try changing Line 8 to `video= cv.VideoWriter("path\Screen Recording .avi",cv.VideoWriter_fourcc(*'MJPG'),20, size)`

2. OpenCv Can give problems running on WSL. 
>Refer : [https://dev.to/naruaika/using-opencv-on-windows-subsystem-for-linux-1ako](url)

If there is a specific error coming up, please share that.
